apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-server
  labels:
    io.kompose.service: simple-k8s-server
spec:
  type: NodePort
  selector:
    io.kompose.service: simple-k8s-server
  ports:
  - port: 9090