version: "2"

services:

  consul:
    image: consul:latest
    ports: 
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    links: 
      - gin-web-01
      - gin-web-02
    networks:
      - sky-net
  
  gin-web-01:
    image: gin-web:1.0.1
    environment: 
      - PORT=8080
    ports: 
      - "8080:8080"
    command: /go/bin/gin-web
    networks:
      - sky-net
  
  gin-web-02:
    image: gin-web:1.0.1
    environment:
      - PORT=9090
    ports: 
      - "9090:9090"
    command: /go/bin/gin-web
    networks:
      - sky-net

  simple-server:
    build:
      context: .
      dockerfile: ../server-service/Dockerfile
    image: simple-server:1.0.1
    environment: 
      - CONSUL_HTTP_ADDR=consul:8500
    command: /go/bin/server
    depends_on: 
      - consul
    networks: 
      - sky-net

  simple-client:
    build: 
      context: .
      dockerfile: ../client-service/Dockerfile
    image: simple-client:1.0.1
    environment: 
      - CONSUL_HTTP_ADDR=consul:8500
    command: /go/bin/client
    depends_on: 
      - consul
    networks: 
      - sky-net

networks:
  sky-net:
    driver: bridge
    