version: "2"

services:

  consul:
    image: consul:latest
    ports: 
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  proto-server:
    build:
      context: .
      dockerfile: ../proto-server/Dockerfile
    image:  proto-server:1.0.1
    environment: 
      - CONSUL_HTTP_ADDR=consul:8500
    command: /go/bin/micro-server
    depends_on: 
      - consul
    networks: 
      - sky-net

  proto-client:
    build: 
      context: .
      dockerfile: ../proto-client/Dockerfile
    image:  proto-client:1.0.1
    environment: 
      - CONSUL_HTTP_ADDR=consul:8500
    command: /go/bin/micro-client
    depends_on: 
      - consul
    networks: 
      - sky-net
    ports: 
      - "8081:8081"

  hystrix-dashboard:
    image: mlabouardy/hystrix-dashboard:latest
    ports: 
      - "7979:7979"
      - "9002:9002"
    networks:
      - sky-net
networks:
  sky-net:
    driver: bridge
    